In [39]:
import numpy as np

## <i><b> from ase.build import molecule</b></i>

In [40]:
from ase.build import molecule 
h2o = molecule('H2O')

In [41]:
ai = h2o.get_chemical_symbols(); print(ai)
ri = h2o.get_positions(); print(ri)

['O', 'H', 'H']
[[ 0.        0.        0.119262]
 [ 0.        0.763239 -0.477047]
 [ 0.       -0.763239 -0.477047]]


Note: Only molecules that exist in the ASE molecule library will work. <br>
Example, C<sub>7</sub>H<sub>16</sub> molecule is NOT present in the library. <br>
Solution: SMILES => RDKit/Obabel (initial geometry) => ASE  

#### <i><b>ase.io</b></i>

In [42]:
from ase.io import read,write

In [43]:
mol = read('../_files_/phenol.xyz') # --- read the xyz file
ai = mol.get_chemical_symbols(); print(ai)

['C', 'C', 'C', 'C', 'C', 'C', 'O', 'H', 'H', 'H', 'H', 'H', 'H']


#### <i><b>get_distance()</b></i>

In [44]:
dist = mol.get_distance(6,12); print(dist) # O-H bond length

0.9709727090397546


#### <i><b>get_all_distances()</b></i>

In [45]:
dists = mol.get_all_distances(); print(np.round(dists, 2))

[[0.   1.39 2.42 2.79 2.42 1.39 2.36 1.09 2.15 3.4  3.88 3.41 3.16]
 [1.39 0.   1.4  2.42 2.79 2.41 3.64 2.16 1.09 2.15 3.4  3.88 4.31]
 [2.42 1.4  0.   1.4  2.42 2.78 4.14 3.4  2.16 1.09 2.15 3.4  4.56]
 [2.79 2.42 1.4  0.   1.4  2.41 3.67 3.88 3.4  2.16 1.09 2.15 3.8 ]
 [2.42 2.79 2.42 1.4  0.   1.39 2.4  3.4  3.88 3.4  2.16 1.09 2.41]
 [1.39 2.41 2.78 2.41 1.39 0.   1.36 2.15 3.39 3.87 3.39 2.16 1.91]
 [2.36 3.64 4.14 3.67 2.4  1.36 0.   2.58 4.51 5.23 4.55 2.68 0.97]
 [1.09 2.16 3.4  3.88 3.4  2.15 2.58 0.   2.48 4.3  4.96 4.3  3.53]
 [2.15 1.09 2.16 3.4  3.88 3.39 4.51 2.48 0.   2.48 4.3  4.97 5.27]
 [3.4  2.15 1.09 2.16 3.4  3.87 5.23 4.3  2.48 0.   2.48 4.29 5.63]
 [3.88 3.4  2.15 1.09 2.16 3.39 4.55 4.96 4.3  2.48 0.   2.47 4.51]
 [3.41 3.88 3.4  2.15 1.09 2.16 2.68 4.3  4.97 4.29 2.47 0.   2.26]
 [3.16 4.31 4.56 3.8  2.41 1.91 0.97 3.53 5.27 5.63 4.51 2.26 0.  ]]


#### <i><b>get_angle()</b></i>

In [46]:
theta = mol.get_angle(5,6,12); print(theta)

108.4706493715955


#### <i><b>get_dihedral()</b></i>

In [47]:
theta = mol.get_dihedral(4,5,6,12); print(theta)

358.8903545003642


#### <i><b>set_dihedral()</b></i>

In [48]:
for dihedral in [0,90,120]:

    new_mol = mol.copy() # --- Shallow Copy
    new_mol.set_dihedral(4,5,6,12,dihedral)
    
    write(f"../_files_/phenol_dihedral_{dihedral:03d}.xyz", new_mol) # --- Save 